CREATE DATABASE blog;

CREATE TABLE users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  fullname VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL
);


CREATE TABLE categories (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE subCategories (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  parent_id INT UNSIGNED,
  FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE posts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  cat_id INT UNSIGNED,
  sub_cat_id INT UNSIGNED,
  author_id INT UNSIGNED,
  title VARCHAR(100) NOT NULL,
  image VARCHAR(100),
  content VARCHAR(1000) NOT NULL,
  FOREIGN KEY (cat_id) REFERENCES categories(id),
  FOREIGN KEY (sub_cat_id) REFERENCES subCategories(id),
  FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE TABLE comments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  comment VARCHAR(500) NOT NULL,
  post_id INT UNSIGNED,
  author_id INT UNSIGNED,
  FOREIGN KEY (post_id) REFERENCES posts(id),
  FOREIGN KEY (author_id) REFERENCES users(id)
);
